if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42285,'CaCO3','C',1)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42285,'INOR_C','C',0.12)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'CaCO3','C',0.45)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'H','CNS',0.62)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'HI','RE',187)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'INOR_C','C',0.054)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'NIT','CNS',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'OI','RE',56)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'ORG_C','CNS',0.6)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'PC','RE',0.07)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'PI','RE',0.1)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'S1','RE',0.09)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'S2','RE',0.77)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'S3','RE',0.23)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'SUL','CNS',0.06)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'TMX','RE',460)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'TOC','RE',0.41)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42290,'TOT_C','CNS',0.65)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42295,'CaCO3','C',0.45)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (42295,'INOR_C','C',0.054)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3295,'CaCO3','C',73.91)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3295,'H','CNS',0.27)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3295,'INOR_C','C',8.87)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3295,'ORG_C','CNS',0.11)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3295,'TOT_C','CNS',8.98)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3300,'CaCO3','C',76.07)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3300,'H','CNS',0.24)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3300,'INOR_C','C',9.13)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3300,'ORG_C','CNS',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3300,'TOT_C','CNS',9.11)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3240,'CaCO3','C',70.97)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3240,'H','CNS',0.15)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3240,'INOR_C','C',8.52)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3240,'ORG_C','CNS',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3240,'TOT_C','CNS',8.24)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3245,'CaCO3','C',82.33)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3245,'H','CNS',0.09)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3245,'INOR_C','C',9.88)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3245,'ORG_C','CNS',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3245,'TOT_C','CNS',9.6)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'CaCO3','C',29.66)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'H','CNS',0.5)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'INOR_C','C',3.56)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'ORG_C','CNS',0.08)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'PI','RE',0.25)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'S1','RE',0.02)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'S2','RE',0.1)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'S3','RE',1.92)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'TMX','RE',413)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'TOC','RE',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'TOT_C','CNS',3.64)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'CaCO3','C',29.66)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'H','CNS',0.5)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'INOR_C','C',3.56)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'ORG_C','CNS',0.08)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'PI','RE',0.25)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'S1','RE',0.02)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'S2','RE',0.1)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'S3','RE',1.92)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'TMX','RE',413)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'TOC','RE',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3250,'TOT_C','CNS',3.64)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'CaCO3','C',63.12)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'H','CNS',0.24)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'HI','RE',50)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'INOR_C','C',7.58)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'OI','RE',1675)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'ORG_C','CNS',0.16)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'PI','RE',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'S1','RE',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'S2','RE',0.04)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'S3','RE',1.34)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'TMX','RE',410)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'TOC','RE',0.08)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'TOT_C','CNS',7.74)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'CaCO3','C',63.12)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'H','CNS',0.24)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'HI','RE',50)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'INOR_C','C',7.58)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'OI','RE',1675)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'ORG_C','CNS',0.16)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'PI','RE',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'S1','RE',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'S2','RE',0.04)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'S3','RE',1.34)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'TMX','RE',410)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'TOC','RE',0.08)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3255,'TOT_C','CNS',7.74)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'CaCO3','C',55.44)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'H','CNS',0.46)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'HI','RE',543)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'INOR_C','C',6.66)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'NIT','CNS',0.014)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'OI','RE',152)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'ORG_C','CNS',1.68)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'PI','RE',0.01)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'S1','RE',0.08)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'S2','RE',6.6)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'S3','RE',1.86)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'TMX','RE',403)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'TOC','RE',1.22)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'TOT_C','CNS',8.34)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'CaCO3','C',55.44)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'H','CNS',0.46)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'HI','RE',543)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'INOR_C','C',6.66)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'NIT','CNS',0.014)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'OI','RE',152)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'ORG_C','CNS',1.68)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'PI','RE',0.01)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'S1','RE',0.08)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'S2','RE',6.6)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'S3','RE',1.86)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'TMX','RE',403)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'TOC','RE',1.22)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3260,'TOT_C','CNS',8.34)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'CaCO3','C',51.53)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'H','CNS',0.64)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'INOR_C','C',6.19)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'NIT','CNS',0.04)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'ORG_C','CNS',2.97)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'TOT_C','CNS',9.16)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'CaCO3','C',51.53)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'H','CNS',0.64)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'INOR_C','C',6.19)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'NIT','CNS',0.04)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'ORG_C','CNS',2.97)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3265,'TOT_C','CNS',9.16)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'CaCO3','C',74.48)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'H','CNS',0.34)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'HI','RE',605)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'INOR_C','C',8.94)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'NIT','CNS',0.012)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'OI','RE',85)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'ORG_C','CNS',1.69)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'PI','RE',0.01)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'S1','RE',0.1)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'S2','RE',8.4)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'S3','RE',1.19)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'SUL','CNS',0.1)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'TMX','RE',395)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'TOC','RE',1.39)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'TOT_C','CNS',10.63)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'CaCO3','C',74.48)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'H','CNS',0.34)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'HI','RE',605)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'INOR_C','C',8.94)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'NIT','CNS',0.012)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'OI','RE',85)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'ORG_C','CNS',1.69)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'PI','RE',0.01)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'S1','RE',0.1)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'S2','RE',8.4)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'S3','RE',1.19)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'SUL','CNS',0.1)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'TMX','RE',395)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'TOC','RE',1.39)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3270,'TOT_C','CNS',10.63)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'CaCO3','C',41.65)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'H','CNS',0.73)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'HI','RE',485)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'INOR_C','C',5)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'NIT','CNS',0.038)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'OI','RE',79)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'ORG_C','CNS',3.99)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'PI','RE',0.01)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'S1','RE',0.18)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'S2','RE',15.6)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'S3','RE',2.55)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'TMX','RE',406)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'TOC','RE',3.2)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'TOT_C','CNS',8.99)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'CaCO3','C',41.65)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'H','CNS',0.73)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'HI','RE',485)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'INOR_C','C',5)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'NIT','CNS',0.038)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'OI','RE',79)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'ORG_C','CNS',3.99)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'PI','RE',0.01)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'S1','RE',0.18)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'S2','RE',15.6)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'S3','RE',2.55)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'TMX','RE',406)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'TOC','RE',3.2)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3275,'TOT_C','CNS',8.99)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'CaCO3','C',49.76)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'H','CNS',1.54)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'HI','RE',699)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'INOR_C','C',5.97)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'NIT','CNS',0.16)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'OI','RE',45)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'ORG_C','CNS',11.45)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'PI','RE',0.02)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'S1','RE',1.35)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'S2','RE',70.9)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'S3','RE',4.63)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'SUL','CNS',0.62)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'TMX','RE',393)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'TOC','RE',10.14)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'TOT_C','CNS',17.42)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'CaCO3','C',49.76)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'H','CNS',1.54)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'HI','RE',699)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'INOR_C','C',5.97)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'NIT','CNS',0.16)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'OI','RE',45)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'ORG_C','CNS',11.45)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'PI','RE',0.02)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'S1','RE',1.35)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'S2','RE',70.9)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'S3','RE',4.63)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'SUL','CNS',0.62)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'TMX','RE',393)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'TOC','RE',10.14)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3280,'TOT_C','CNS',17.42)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'CaCO3','C',51.2)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'H','CNS',0.85)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'INOR_C','C',6.15)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'NIT','CNS',0.085)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'ORG_C','CNS',5.39)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'TOT_C','CNS',11.54)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'CaCO3','C',51.2)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'H','CNS',0.85)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'INOR_C','C',6.15)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'NIT','CNS',0.085)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'ORG_C','CNS',5.39)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3285,'TOT_C','CNS',11.54)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3290,'CaCO3','C',88.42)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3290,'H','CNS',0.007)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3290,'INOR_C','C',10.61)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3290,'ORG_C','CNS',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3290,'TOT_C','CNS',10.43)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3290,'CaCO3','C',88.42)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3290,'H','CNS',0.007)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3290,'INOR_C','C',10.61)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3290,'ORG_C','CNS',0)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (3290,'TOT_C','CNS',10.43)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8171,'HI','RE',451)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8171,'OI','RE',70)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8171,'PI','RE',0.01)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8171,'S1','RE',0.26)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8171,'S2','RE',20.6)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8171,'S3','RE',3.24)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8171,'TMX','RE',407)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8171,'TOC','RE',4.57)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8176,'OI','RE',1016)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8176,'PI','RE',0.04)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8176,'S1','RE',0.03)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8176,'S2','RE',0.8)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8176,'S3','RE',0.61)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8176,'TMX','RE',445)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_ANALYSIS_TEST (RUN_ID,ANALYSIS_CODE,METHOD_CODE,ANALYSIS_RESULT) values (8176,'TOC','RE',0.06)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (42285,114942,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (42290,114943,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (42295,114944,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3295,25277,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3300,25263,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3240,25061,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3245,25063,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3250,25107,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3250,25107,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3255,25106,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3255,25106,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3260,25105,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3260,25105,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3265,25102,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3265,25102,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3270,25104,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3270,25104,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3275,25103,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3275,25103,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3280,25101,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3280,25101,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3285,25100,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3285,25100,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3290,25099,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (3290,25099,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (8171,227155,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_CHEM_CARB_SAMPLE_TEST (RUN_ID,SAMPLE_ID,LOCATION) values (8176,227154,'SHI')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_HOLE_TEST (LEG,SITE,HOLE) values (171,1049,'B')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SAMPLE_TEST (SAMPLE_ID,LOCATION,SAM_SECTION_ID,TOP_INTERVAL,BOTTOM_INTERVAL) values (25099,'SHI',42830,0.21,0.22)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SAMPLE_TEST (SAMPLE_ID,LOCATION,SAM_SECTION_ID,TOP_INTERVAL,BOTTOM_INTERVAL) values (25100,'SHI',42830,0.19,0.21)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SAMPLE_TEST (SAMPLE_ID,LOCATION,SAM_SECTION_ID,TOP_INTERVAL,BOTTOM_INTERVAL) values (25101,'SHI',42830,0.175,0.19)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SAMPLE_TEST (SAMPLE_ID,LOCATION,SAM_SECTION_ID,TOP_INTERVAL,BOTTOM_INTERVAL) values (25102,'SHI',42830,0.125,0.22)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SAMPLE_TEST (SAMPLE_ID,LOCATION,SAM_SECTION_ID,TOP_INTERVAL,BOTTOM_INTERVAL) values (25103,'SHI',42830,0.16,0.175)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SAMPLE_TEST (SAMPLE_ID,LOCATION,SAM_SECTION_ID,TOP_INTERVAL,BOTTOM_INTERVAL) values (25104,'SHI',42830,0.135,0.16)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SAMPLE_TEST (SAMPLE_ID,LOCATION,SAM_SECTION_ID,TOP_INTERVAL,BOTTOM_INTERVAL) values (25105,'SHI',42830,0.125,0.135)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SAMPLE_TEST (SAMPLE_ID,LOCATION,SAM_SECTION_ID,TOP_INTERVAL,BOTTOM_INTERVAL) values (25106,'SHI',42830,0.085,0.125)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SAMPLE_TEST (SAMPLE_ID,LOCATION,SAM_SECTION_ID,TOP_INTERVAL,BOTTOM_INTERVAL) values (25107,'SHI',42830,0.07,0.085)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SAMPLE_TEST (SAMPLE_ID,LOCATION,SAM_SECTION_ID,TOP_INTERVAL,BOTTOM_INTERVAL) values (227154,'SHI',42830,0.205,0.22)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SAMPLE_TEST (SAMPLE_ID,LOCATION,SAM_SECTION_ID,TOP_INTERVAL,BOTTOM_INTERVAL) values (227155,'SHI',42830,0.19,0.205)`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42730,1,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42730,1,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42830,3,'C',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42740,3,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42830,3,'C',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42740,3,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42830,3,'C',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42740,3,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42830,3,'C',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42745,4,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42830,3,'C',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42745,4,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42830,3,'C',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42745,4,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42830,3,'C',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42745,4,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42830,3,'C',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42745,4,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42830,3,'C',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42745,4,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42735,2,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42735,2,'S',171,1049,'B',8,'H')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42820,1,'S',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42820,1,'S',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42820,1,'S',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42830,3,'C',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }
if _, err := testDb.Exec(`Insert into OCD_SECTION_TEST (SECTION_ID,SECTION_NUMBER,SECTION_TYPE,LEG,SITE,HOLE,CORE,CORE_TYPE) values (42830,3,'C',171,1049,'B',11,'X')`, ); err != nil {t.Fatal(err) }