version: '3.1'

services:

    db:
        image: nawer/blazegraph
        environment:
            JAVA_XMS: 512m
            JAVA_XMX: 1g
        volumes:
                - /home/fils/Data/CSDCO/blazegraph:/var/lib/blazegraph
              #- ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "9999:9999"



